date: now
date-format: "YYYY-MM-DD HH:mm z"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
    toc-depth: 3
    toc-expand: 2
    number-sections: true
    # embed-resources: true
editor:
  mode: source
editor_options:
  chunk_output_type: console
