---
title: "Extractr"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Get Data using `extractr`

```{r}
# devtools::install_local("/share/github/marinebon/extractr", force = T)
devtools::load_all("/share/github/marinebon/extractr")
# TODO: extractr -- git commit, push 
librarian::shelf(
  dplyr, DT, furrr, glue, here, lubridate, mapview, purrr, readr, sf, stringr, terra,
  marinebon/extractr)

sanctuaries <- readRDS(here("../climate-dashboard/data/sanctuaries.rds"))
# mapView(sanctuaries)
# sanctuaries |>
#   st_drop_geometry() |>
#   datatable()

dir_out <- here("data/NOAA_DHW")

# CoralTemp eddaily
ed <- ed_info("https://coastwatch.pfeg.noaa.gov/erddap/griddap/NOAA_DHW.html")   # CoralTemp eddaily
times <- ed_dim(ed, "time")
# (vars <- ed_vars(ed))
v <- "CRW_SST"

sanctuary_years <- sanctuaries |> 
  st_drop_geometry() |> 
  arrange(nms) |> 
  select(nms) |> 
  cross_join(
    tibble(
      year = year(min(times)):year(max(times)))) |> 
  # TODO: remove DEBUG
  filter(
    !nms %in% c("CINMS","FKNMS"),                # TODO: update '24
    !nms %in% c("CBNMS","CPNMS","FGBNMS","GFNMS","GRNMS","HIHWNMS","MBNMS","SBNMS"), # done '24-08-28
    !(nms == "MBNMS-david" & year < 1986),
    !(nms == "SBNMS"       & year < 2022))
# View(sanctuary_years)

# rerddap::cache_delete_all()

# TODO: GDAL Message 1: Metadata exceeding 32000 bytes cannot be written into GeoTIFF. Transferred to PAM instead.
# TODO: retry if code=500 like...
  # HIHWNMS, 2020
  # Downloading 15 requests, up to 25 time slices each
  # ...
  # Fetching request 4 of 15 (2020-03-16 to 2020-04-09) ~ 08:06:54 UTC
  # Error : Error {
  #     code=500;
  #     message="Internal Server Error:
  #       FileNotFoundException:
  #         /usr/local/erddap/cache/km/dhw_5km/f631_ca87_9367_570740621_0
  #       (No such file or directory)" ; }
  # MBNMS-david, 1986
  # Downloading 1 requests, up to 1250 time slices each
  # Fetching request 1 of 1 (1986-01-01 to 1986-12-31) ~ 13:07:20 UTC
  # Error : Error {
  #     code=500;
  #     message="Internal Server Error: FileNotFoundException: /usr/local/erddap/cache/km/dhw_5km/6f3e_396a_1a53_1437553582_0 (No such file or directory)";
  # }

# n_cores <- parallel::detectCores() - 1
# plan(multisession, workers = n_cores)

# View(sanctuary_years)

sanctuary_years |> 
  # slice(21:nrow(sanctuary_years)) |> 
  # future_pmap(
  pmap(
    \(nms, year){   #  nms = "CBNMS"; year = 1985   # DEBUG
      message(glue::glue("{nms}, {year}"))
      
      times_yr <- times[lubridate::year(times) == year]
      
      ply <- sanctuaries |> 
        dplyr::filter(nms == !!nms)
      bb <- sf::st_bbox(ply)
      # TODO: consider expanding by 10% and rounding 2 digits
      # |> stars:::bb_shrink(-0.1) |> round(2)
      
      extractr::ed_extract(
        ed, 
        var       = v,
        sf_zones  = ply,
        bbox      = bb,
        rast_tif  = glue::glue("{dir_out}/{nms}/{year}.tif"),
        zonal_csv = glue::glue("{dir_out}/{nms}/{year}.csv"),
        dir_nc    = glue::glue("{dir_out}/{nms}/{year}_nc"),
        time_min  = min(times_yr),
        time_max  = max(times_yr))
    })  
    # },
    # .options = furrr_options(
    #   packages = c("dplyr","extractr","glue","lubridate","sf"),
    #   globals  = c("dir_out","ed","sanctuaries","times","v"),
    #   seed     = T))
```

### DEBUG

```{r}
tif <- "~/Github/noaa-onms/climate-dashboard-app/data/noaacrwsstDaily/FKNMS/2024.tif"
tif <- "/Users/bbest/Downloads/climate-dashboard-data-noaacrwsstDaily_CINMS-FKNMS/FKNMS/2024.tif"
r <- rast(tif)
nlyr(r)
values(subset(r, 1), na.rm=T)

plet(subset(r, 1))
terra::time(r)
terra::plet(rast(r, 1))

mapview(r[1])

```

    Error in open.connection(structure(3L, class = c("curl", "connection"), conn_id = <pointer: 0x18f0>),  : 
      Timeout was reached: [coastwatch.pfeg.noaa.gov] Resolving timed out after 10004 milliseconds
    Error in FUN(X[[i]], ...) : 
      Problem fetching dimension time from ERDDAP: https://coastwatch.pfeg.noaa.gov/erddap/griddap/NOAA_DHW.csvp?time
